import 'package:flutter/material.dart';
import 'package:reddit/widgets/post.dart';

final List<Post> testPosts = [
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
  Post(
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
  ),
];
