import 'package:reddit/widgets/post.dart';

final List<Post> testPosts = [
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
       deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
        pollVote: null,
  ),
  Post(
        vote: 0,
                isSaved: false,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
        deleted:  false,
        pollVote: null,
  ),
  Post(
        vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
        deleted:  false,
        isSaved: false,
        pollVote: null,
  ),
  Post(
        deleted:  false,
        vote: 0,
    isLocked: false,
            isSaved: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
    deleted: false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
    deleted: false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
    deleted: false,
    pollExpired: false,
    pollVote: null,
  ),
  Post(
    vote: 0,
    isLocked: false,
    id: "1",
    imageUrl: "assets/images/profile.png",
    name: "John Doe",
    title: "Flutter is the best",
    postContent: "Flutter is the best",
    date: "2021-09-09",
    likes: 4,
    commentsCount: 1,
    communityName: "r/FlutterDev",
    isSaved: false,
        deleted:  false,
    pollExpired: false,
    pollVote: null,
  ),
];
